components {
  id: "player_control"
  component: "/game/player/player_control.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"player_64_64\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/player.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player\"\n"
  "mask: \"default\"\n"
  "mask: \"enemy_bullet\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "    id: \"player_collider\"\n"
  "  }\n"
  "  data: 32.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "bullet_factory"
  type: "factory"
  data: "prototype: \"/game/bullet_player/bullet_player.go\"\n"
  ""
}
